version: '3'

services:
  server:
    build:
      context: ./TournaME
      dockerfile: Dockerfile
    ports:
      - "3124:3124"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tourname
    networks:
      - app-network

  client:
    build:
      context: ./TournaME-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: