name: Build Server and Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TournaME

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './TournaME/package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Server
      run: npm run build

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TournaME-client

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './TournaME-client/package-lock.json'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Next.js App
      run: npm run build